model:
  name: mnist64fc
  path: ../mnist_fc.pt
data:
  dataset: MNIST
  start: 0
  end: 20
  std: [1.]
  mean: [0.]
specification:
  epsilon: 0.2
  norm: .inf
attack:
  pgd_order: after
solver:
  batch_size: 4096
  beta-crown:
    iteration: 20
bab:
  timeout: 180
